// Code generated by mockery v2.53.3. DO NOT EDIT.

//go:build !compile

package edit

import (
	history "github.com/ksysoev/wsget/pkg/repo/history"
	mock "github.com/stretchr/testify/mock"
)

// MockFuzzySearchableHistory is an autogenerated mock type for the FuzzySearchableHistory type
type MockFuzzySearchableHistory struct {
	mock.Mock
}

type MockFuzzySearchableHistory_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFuzzySearchableHistory) EXPECT() *MockFuzzySearchableHistory_Expecter {
	return &MockFuzzySearchableHistory_Expecter{mock: &_m.Mock}
}

// AddRequest provides a mock function with given fields: req
func (_m *MockFuzzySearchableHistory) AddRequest(req string) {
	_m.Called(req)
}

// MockFuzzySearchableHistory_AddRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddRequest'
type MockFuzzySearchableHistory_AddRequest_Call struct {
	*mock.Call
}

// AddRequest is a helper method to define mock.On call
//   - req string
func (_e *MockFuzzySearchableHistory_Expecter) AddRequest(req interface{}) *MockFuzzySearchableHistory_AddRequest_Call {
	return &MockFuzzySearchableHistory_AddRequest_Call{Call: _e.mock.On("AddRequest", req)}
}

func (_c *MockFuzzySearchableHistory_AddRequest_Call) Run(run func(req string)) *MockFuzzySearchableHistory_AddRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFuzzySearchableHistory_AddRequest_Call) Return() *MockFuzzySearchableHistory_AddRequest_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFuzzySearchableHistory_AddRequest_Call) RunAndReturn(run func(string)) *MockFuzzySearchableHistory_AddRequest_Call {
	_c.Run(run)
	return _c
}

// FuzzySearch provides a mock function with given fields: query
func (_m *MockFuzzySearchableHistory) FuzzySearch(query string) []history.FuzzyMatch {
	ret := _m.Called(query)

	if len(ret) == 0 {
		panic("no return value specified for FuzzySearch")
	}

	var r0 []history.FuzzyMatch
	if rf, ok := ret.Get(0).(func(string) []history.FuzzyMatch); ok {
		r0 = rf(query)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]history.FuzzyMatch)
		}
	}

	return r0
}

// MockFuzzySearchableHistory_FuzzySearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FuzzySearch'
type MockFuzzySearchableHistory_FuzzySearch_Call struct {
	*mock.Call
}

// FuzzySearch is a helper method to define mock.On call
//   - query string
func (_e *MockFuzzySearchableHistory_Expecter) FuzzySearch(query interface{}) *MockFuzzySearchableHistory_FuzzySearch_Call {
	return &MockFuzzySearchableHistory_FuzzySearch_Call{Call: _e.mock.On("FuzzySearch", query)}
}

func (_c *MockFuzzySearchableHistory_FuzzySearch_Call) Run(run func(query string)) *MockFuzzySearchableHistory_FuzzySearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFuzzySearchableHistory_FuzzySearch_Call) Return(_a0 []history.FuzzyMatch) *MockFuzzySearchableHistory_FuzzySearch_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFuzzySearchableHistory_FuzzySearch_Call) RunAndReturn(run func(string) []history.FuzzyMatch) *MockFuzzySearchableHistory_FuzzySearch_Call {
	_c.Call.Return(run)
	return _c
}

// NextRequest provides a mock function with no fields
func (_m *MockFuzzySearchableHistory) NextRequest() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for NextRequest")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFuzzySearchableHistory_NextRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NextRequest'
type MockFuzzySearchableHistory_NextRequest_Call struct {
	*mock.Call
}

// NextRequest is a helper method to define mock.On call
func (_e *MockFuzzySearchableHistory_Expecter) NextRequest() *MockFuzzySearchableHistory_NextRequest_Call {
	return &MockFuzzySearchableHistory_NextRequest_Call{Call: _e.mock.On("NextRequest")}
}

func (_c *MockFuzzySearchableHistory_NextRequest_Call) Run(run func()) *MockFuzzySearchableHistory_NextRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFuzzySearchableHistory_NextRequest_Call) Return(_a0 string) *MockFuzzySearchableHistory_NextRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFuzzySearchableHistory_NextRequest_Call) RunAndReturn(run func() string) *MockFuzzySearchableHistory_NextRequest_Call {
	_c.Call.Return(run)
	return _c
}

// PrevRequest provides a mock function with no fields
func (_m *MockFuzzySearchableHistory) PrevRequest() string {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for PrevRequest")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFuzzySearchableHistory_PrevRequest_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PrevRequest'
type MockFuzzySearchableHistory_PrevRequest_Call struct {
	*mock.Call
}

// PrevRequest is a helper method to define mock.On call
func (_e *MockFuzzySearchableHistory_Expecter) PrevRequest() *MockFuzzySearchableHistory_PrevRequest_Call {
	return &MockFuzzySearchableHistory_PrevRequest_Call{Call: _e.mock.On("PrevRequest")}
}

func (_c *MockFuzzySearchableHistory_PrevRequest_Call) Run(run func()) *MockFuzzySearchableHistory_PrevRequest_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFuzzySearchableHistory_PrevRequest_Call) Return(_a0 string) *MockFuzzySearchableHistory_PrevRequest_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFuzzySearchableHistory_PrevRequest_Call) RunAndReturn(run func() string) *MockFuzzySearchableHistory_PrevRequest_Call {
	_c.Call.Return(run)
	return _c
}

// ResetPosition provides a mock function with no fields
func (_m *MockFuzzySearchableHistory) ResetPosition() {
	_m.Called()
}

// MockFuzzySearchableHistory_ResetPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetPosition'
type MockFuzzySearchableHistory_ResetPosition_Call struct {
	*mock.Call
}

// ResetPosition is a helper method to define mock.On call
func (_e *MockFuzzySearchableHistory_Expecter) ResetPosition() *MockFuzzySearchableHistory_ResetPosition_Call {
	return &MockFuzzySearchableHistory_ResetPosition_Call{Call: _e.mock.On("ResetPosition")}
}

func (_c *MockFuzzySearchableHistory_ResetPosition_Call) Run(run func()) *MockFuzzySearchableHistory_ResetPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFuzzySearchableHistory_ResetPosition_Call) Return() *MockFuzzySearchableHistory_ResetPosition_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFuzzySearchableHistory_ResetPosition_Call) RunAndReturn(run func()) *MockFuzzySearchableHistory_ResetPosition_Call {
	_c.Run(run)
	return _c
}

// Search provides a mock function with given fields: prefix
func (_m *MockFuzzySearchableHistory) Search(prefix string) string {
	ret := _m.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(prefix)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// MockFuzzySearchableHistory_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockFuzzySearchableHistory_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - prefix string
func (_e *MockFuzzySearchableHistory_Expecter) Search(prefix interface{}) *MockFuzzySearchableHistory_Search_Call {
	return &MockFuzzySearchableHistory_Search_Call{Call: _e.mock.On("Search", prefix)}
}

func (_c *MockFuzzySearchableHistory_Search_Call) Run(run func(prefix string)) *MockFuzzySearchableHistory_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockFuzzySearchableHistory_Search_Call) Return(_a0 string) *MockFuzzySearchableHistory_Search_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockFuzzySearchableHistory_Search_Call) RunAndReturn(run func(string) string) *MockFuzzySearchableHistory_Search_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockFuzzySearchableHistory creates a new instance of MockFuzzySearchableHistory. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFuzzySearchableHistory(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFuzzySearchableHistory {
	mock := &MockFuzzySearchableHistory{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
