// Code generated by mockery v2.46.3. DO NOT EDIT.

//go:build !compile

package core

import mock "github.com/stretchr/testify/mock"

// MockEditor is an autogenerated mock type for the Editor type
type MockEditor struct {
	mock.Mock
}

type MockEditor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEditor) EXPECT() *MockEditor_Expecter {
	return &MockEditor_Expecter{mock: &_m.Mock}
}

// Close provides a mock function with given fields:
func (_m *MockEditor) Close() error {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Close")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func() error); ok {
		r0 = rf()
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockEditor_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type MockEditor_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *MockEditor_Expecter) Close() *MockEditor_Close_Call {
	return &MockEditor_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *MockEditor_Close_Call) Run(run func()) *MockEditor_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEditor_Close_Call) Return(_a0 error) *MockEditor_Close_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockEditor_Close_Call) RunAndReturn(run func() error) *MockEditor_Close_Call {
	_c.Call.Return(run)
	return _c
}

// Edit provides a mock function with given fields: keyStream, initBuffer
func (_m *MockEditor) Edit(keyStream <-chan KeyEvent, initBuffer string) (string, error) {
	ret := _m.Called(keyStream, initBuffer)

	if len(ret) == 0 {
		panic("no return value specified for Edit")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(<-chan KeyEvent, string) (string, error)); ok {
		return rf(keyStream, initBuffer)
	}
	if rf, ok := ret.Get(0).(func(<-chan KeyEvent, string) string); ok {
		r0 = rf(keyStream, initBuffer)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(<-chan KeyEvent, string) error); ok {
		r1 = rf(keyStream, initBuffer)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockEditor_Edit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Edit'
type MockEditor_Edit_Call struct {
	*mock.Call
}

// Edit is a helper method to define mock.On call
//   - keyStream <-chan KeyEvent
//   - initBuffer string
func (_e *MockEditor_Expecter) Edit(keyStream interface{}, initBuffer interface{}) *MockEditor_Edit_Call {
	return &MockEditor_Edit_Call{Call: _e.mock.On("Edit", keyStream, initBuffer)}
}

func (_c *MockEditor_Edit_Call) Run(run func(keyStream <-chan KeyEvent, initBuffer string)) *MockEditor_Edit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(<-chan KeyEvent), args[1].(string))
	})
	return _c
}

func (_c *MockEditor_Edit_Call) Return(_a0 string, _a1 error) *MockEditor_Edit_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockEditor_Edit_Call) RunAndReturn(run func(<-chan KeyEvent, string) (string, error)) *MockEditor_Edit_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockEditor creates a new instance of MockEditor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEditor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEditor {
	mock := &MockEditor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
